### ISSUE TITLE
scala-native support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka-js/shocon#32]
please publish `*.nir` artifacts, for, i.e. https://github.com/jokade/slogging/issues/26

**Comment by andreaTP** [comment]
first we have to configure the build for it, and verify that it works.

PR are welcome :-)

**Comment by Andrei-Pozolotin** [comment]
will you promise `maven-central` release within 24 hrs of working PR? :-)

**Comment by andreaTP** [comment]
48 hrs if complete with tests :-)

**Comment by Andrei-Pozolotin** [comment]
ok, it’s a deal :-)

**Comment by Andrei-Pozolotin** [comment]
released: 
* fork: [random-scalor](https://github.com/random-scalor/scalor-shocon#random-scalor-release-with-native-support)
* artifact: [maven-central](http://search.maven.org/#search%7Cga%7C1%7Ccom.carrotgarden.shocon)

works fine, but surprisingly `native` feels slow compared to similar `jvm` code
