### ISSUE TITLE
Maximum String literal length exceeded

### ISSUE THREAD

**Issue by 2m** [akka-js/shocon#39]
When compiling a project that depends on Akka Http. The concatenated `shocon.conf` is just over 2000 lines.

**Comment by andreaTP** [comment]
I published from this branch: https://github.com/akka-js/shocon/tree/macroTime
version `0.3.0-SNAPSHOT`, would you mind to give it a spin?

**Comment by 2m** [comment]
Where did you publish it? And is the version rather [`0.3.0-PERF`](https://github.com/akka-js/shocon/commit/945e77d8c394ed07c64259f7d8e539d622aeb689#diff-c275e43e5d4ef31cb36384dbbf818da8R9)?

**Comment by 2m** [comment]
Tried it out and it worked like a charm!

**Comment by andreaTP** [comment]
Great to hear! can we close this?
(b.t.w. interested if the project you are referring is open source ...)

**Comment by 2m** [comment]
Yea. We can close this ticket with a milestone of the next release.

Yea, the project I am playing with is a twitter bot that uses Akka: https://github.com/2m/kabrioletas

I was using this project as an excuse to try out GraalVM and its native-image building functionality. And the first line of "defence" I found was typesafe-config usage of Classloaders which I tried to workaround by replacing it with shocon.

**Comment by andreaTP** [comment]
`0.3.1` release today, sorry for the delay I just wanted to clean up my macro implementation :-)

**Comment by 2m** [comment]
This should be assigned to `0.3.1` milestone.

**Comment by andreaTP** [comment]
done thanks :-)
