### ISSUE TITLE
My project does not build SBT settings

### ISSUE THREAD

**Issue by GioAgu17** [akka-js/shocon#46]
Sorry, I am a first-time developer and I ham having troubles in understanding how to use SHocon. My SBT project cannot properly build the settings that I found in the README. After adding the plugin, I get some compilation error when I add the lines on build.sbt. How is it possible?

**Comment by GioAgu17** [comment]
More precisely, when adding to build.sbt the following lines:

    val root = project.in(file(".")
    .enablePlugins(ShoconPlugin)
    .settings(
    libraryDependencies += "org.akka-js" %% "shocon" % "0.4.1",
    // for Scala.js/Native or cross projects use %%% instead:
    // libraryDependencies += "org.akka-js" %%% "shocon" % "0.4.1"

    // add dependency on shocon file generation task
    // (not required, but otherwise you need to call shoconConcat manually before compilation!)
    compile in Compile := (compile in Compile).dependsOn(shoconConcat).value

    /* ... */
    )

I get `error while importing sbt project: [error]: ')' expected but eof found`

I am using IntellijIdea with sbt plugin, version 1.1.0

**Comment by GioAgu17** [comment]
ok, I added an additional ')' and that fixed the previous problem. Now I am getting the following:
    `error: value enablePlugins is not a member of sbt.File`

**Comment by andreaTP** [comment]
the missing closed parenthesis is in the first line:
```
val root = project.in(file("."))
```

**Comment by andreaTP** [comment]
fixed in master, thanks.
