### ISSUE TITLE
shocon.conf "}" at eol on # SOURCE lines?

### ISSUE THREAD

**Issue by larsjaas** [akka-js/shocon#48]
https://github.com/akka-js/shocon/blob/21b3ef56f15089970225ec4f0835b6a37c4fc3a1/plugin/src/main/scala/org/akkajs/shocon/sbtplugin/ShoconPlugin.scala#L59

I'm just wondering if the '}' at the end-of-the-line in the generated shocon.conf file for the SOURCE lines is intentional or a typo?

**Comment by andreaTP** [comment]
I guess is a typo, but the line is commented with a `#` in front, so, it doesn't cause problems.
I'm open to accept a PR removing it. Thanks for reporting!
